/apps/gnome-terminal/:
  global/:
    use_menu_accelerators: false
    use_mnemonics: false
  profiles/Default/:
    default_show_menubar: false
/apps/gnome-power-manager/buttons:
  lid_ac: false
  lid_battery: false
/apps/metacity/:
  general/:
    num_workspaces: 7
    theme: Clearlooks
  global_keybindings/:
    switch_to_workspace_1: <Control>1
    switch_to_workspace_2: <Control>2
    switch_to_workspace_3: <Control>3
    switch_to_workspace_4: <Control>4
    switch_to_workspace_5: <Control>5
    switch_to_workspace_6: <Control>6
    switch_to_workspace_7: <Control>7
  window_keybindings/:
    maximize_vertically: <Alt><Shift>F10
    toggle_maximized: <Alt>F10
    move_to_corner_nw: <Super>1
    move_to_corner_ne: <Super>2
    move_to_corner_se: <Super>o
    move_to_corner_sw: <Super>a
/apps/nautilus/:
  desktop/:
    computer_icon_visible: false
    trash_icon_visible: false
  preferences/:
    always_use_browser: false
    always_use_location_entry: false
    desktop_is_home_dir: true
    no_ubuntu_spatial: true
/desktop/gnome/:
  font_rendering/:
    antialiasing: greyscale
    hinting: slight
  interface/:
    can_change_accels: true
    toolbar_style: icons
    gtk_key_theme: Emacs
    monospace_font_name: Inconsolata Medium 12
